### ISSUE TITLE
Compile error with GHC 7.4.2 

### ISSUE THREAD

**Issue by hvr** [maoe/ghc-prof#1]
Cabal can be informed  either by declaring the dependency on `LambdaCase` via `other-extensions: LambdaCase` or indirectly by setting a lower bound `base >= 4.6`.

```
Configuring component lib from ghc-prof-1.3.0...
Preprocessing library ghc-prof-1.3.0...

src/GHC/Prof/Parser.hs:6:14: Unsupported extension: LambdaCase
```

**Comment by maoe** [comment]
Thanks for reporting the issue. Is there a good way of auto-generating `other-extensions` section (or checking if there are missing or redundant extensions) in a cabal file? It's a bit tedious to maintain it.

Otherwise I think I'll add the lower bound for base.

**Comment by hvr** [comment]
re `other-extensions`: unfortunately not yet; there's some partial support in cabal for that (e.g. `cabal init` generates `other-extensions` for you), but it's not enough. I have some script though which is able to collect `other-extensions`, but I need to polish that up before I can release it... :-)
