### ISSUE TITLE
Can we have a decodeST that requires strict text?

### ISSUE THREAD

**Issue by kindaro** [maoe/ghc-prof#11]
> The representation used by this module is suitable for high performance use and for streaming large quantities of data. It provides a means to manipulate a large body of text without requiring that the entire content be resident in memory.
*[Data.Text.Lazy documentation on Hackage](https://hackage.haskell.org/package/text-1.2.2.2/docs/Data-Text-Lazy.html).*

I don't really see the need for lazy text. Maybe that's because I don't profile really vast programs. To be honest, it's hard for me to imagine a program so vast that its profiling report could not fit in the memory of a modern computer.

I would think strict text would be more suitable for a case when the data is not so immense. So, my proposition: add `decodeST` that would require strict text.

**Comment by maoe** [comment]
Sure, we could add something like `decode' :: T.Text -> Either String Profile` to the API. Are you interested in submitting a PR?

**Comment by kindaro** [comment]
I'll see what I can do, give me 3 days.

**Comment by maoe** [comment]
This has been implemented in #13.
