### ISSUE TITLE
Support GHC 8.4.1

### ISSUE THREAD

**Issue by ndmitchell** [maoe/ghc-prof#14]
Seems the base bound is too restrictive? See https://github.com/fpco/stackage/issues/3393

**Comment by maoe** [comment]
Thanks for reporting. I'll release a new version soon.

**Comment by ndmitchell** [comment]
Thanks! FWIW, because you have an upper bound on the current version, and not on older versions, my code on my CI has actually been using older versions to test with GHC HEAD, so you're history of constraints is such that the upper bound causes people to use older versions which are less likely to work with GHC HEAD.

**Comment by maoe** [comment]
I've just uploaded https://hackage.haskell.org/package/ghc-prof-1.4.1.1.

Also I edited metadata of the older versions. Now they have the constraints of `base >= 4.6 && < 4.10` which I would have done if I did at the time of release.
