### ISSUE TITLE
Broken with GHC 8.0.2

### ISSUE THREAD

**Issue by ndmitchell** [maoe/ghc-prof#4]
I can't guarantee it, and can't share a sample, but you should probably check it still works with the recent GHC 8.0.2. It doesn't appear to, but I hadn't tested with GHC 8.0.1, so can't guarantee if what I was doing was even sensible.

**Comment by maoe** [comment]
Thanks. I'll test it with 8.0.2 on Travis.

**Comment by maoe** [comment]
There seems to be no regression with 8.0.2: https://travis-ci.org/maoe/ghc-prof/jobs/196445198#L535-L540

**Comment by maoe** [comment]
`viewprof` failed with reports that are generated by 8.0.2. I'll take a look.

**Comment by maoe** [comment]
Fixed and released as v1.3.0.2.
